name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build extensions
      run: npm run build

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Add version to artifact names
      run: |
        mv ./dist/HoYoDaily-0.0.0-chrome.zip ./dist/HoYoDaily-${{ steps.get_version.outputs.VERSION }}-chrome.zip
        mv ./dist/HoYoDaily-0.0.0-firefox.zip ./dist/HoYoDaily-${{ steps.get_version.outputs.VERSION }}-firefox.zip

    - name: Upload extensions to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} \
          ./dist/HoYoDaily-${{ steps.get_version.outputs.VERSION }}-chrome.zip \
          ./dist/HoYoDaily-${{ steps.get_version.outputs.VERSION }}-firefox.zip
